apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-ai-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-ai-api
  template:
    metadata:
      labels:
        app: expense-ai-api
    spec:
      containers:
        - name: api
          image: expense-ai:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: expense-ai-api-svc
spec:
  selector:
    app: expense-ai-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
